###
GET  http://127.0.0.1:8000/api/users/?limit=1
Content-Type: application/json
###
###
GET  http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 1eaf500981caa90810df8dcb7c260d222e8407f2
###
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 1eaf500981caa90810df8dcb7c260d222e8407f2

{
  "new_password": "Solnce54",
  "current_password": "Solnce544"
}
###
###
DELETE      http://127.0.0.1:8000/api/users/3/
Content-Type: application/json


###
POST      http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: Token 57e62b17670b781b2436e80950ac9e08150d0ad5


  {
    
    "name": "Капуст",
    "measurement_unit": "кг."
  }

###
POST      http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 57e62b17670b781b2436e80950ac9e08150d0ad5


  {

    "name": "Обед3",
    "color": "#0f0d0a",
    "slug": "dinner"
  }

###
###
POST        http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f

{
  
    
    "name": "Капуста",
    "measurement_unit": "кг"
  
}
###
###
DELETE   http://127.0.0.1:8000/api/recipes/2/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f

{
  "ingredients": [
    {
      "id": 3,
      "amount": 20
    }
        
  ]

}
###
###
GET       http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
###
###
GET       http://127.0.0.1:8000/api/users/subsciptions/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
###

###
GET       http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
###
POST      http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
###
###
DELETE       http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
###


DELETE        http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
######
GET       http://127.0.0.1:8000/api/recipes/2/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
###
POST      http://127.0.0.1:8000/api/recipes/2/favorite/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f

# {
#   "ingredients": [
#     {
#       "id": 3,
#       "amount": 10
#     },
#     {
#       "id": 1,
#       "amount": 15
#     }    
#   ],
#   "tags": [
#     2, 3
#   ],
#   "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
#   "name": "string22",
#   "text": "string",
#   "cooking_time": 1
# }
###
POST       http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f

{
  "ingredients": [
    {
      "id": 3,
      "amount": 10
    },
    {
      "id": 1,
      "amount": 20
    }    
  ],
  "tags": [
    2, 3
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string29",
  "text": "string",
  "cooking_time": 1
}
###
###
GET  http://127.0.0.1:8000/api/recipes/110/
###
PATCH http://127.0.0.1:8000/api/recipes/102/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
# Authorization: Token 538e7dce8d69136abd91691fa4f591bc6bef6eb4

{
  "ingredients": [
    {
      "id": 2,
      "amount": 12
    }    
  ],
  "tags": [
    1
  ],
  "cooking_time": 4

}
###
PATCH http://127.0.0.1:8000/api/recipes/73/
Content-Type: application/json
Authorization: Token 94908c40b7e5e3b8ab6aa378549d88627124d60f
# Authorization: Token 538e7dce8d69136abd91691fa4f591bc6bef6eb4

{

  
  
  
  "cooking_time": 2
}
###
POST      http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 57e62b17670b781b2436e80950ac9e08150d0ad5


  {
    "id": 0,
    "name": "Ужин",
    "color": "#E26C2D",
    "slug": "Supper"
  }


###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 538e7dce8d69136abd91691fa4f591bc6bef6eb4
###
POST   http://127.0.0.1:8000/api/users/
Content-Type: application/json


{
    "first_name": "Иван",
    "last_name": "Иванов",
    "email": "test3@mail.ru",
    "username": "test3.user",
    "password": "Solnce544"
}
###
###
POST   http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json


{
    "first_name": "Иван",
    "last_name": "Иванов",
    "email": "fk@mail.ru",
    "username": "test.user",
    "password": "Solnce544"
}
###
###
GET  http://127.0.0.1:8000/api/users/
Content-Type: application/json

###
###
DELETE   http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Token 1eaf500981caa90810df8dcb7c260d222e8407f2
######
POST  http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token b10f0625e550349680d4919b71d18a8fb6898905
###

###
POST  http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json

###
###
POST  http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "test2@mail.ru",
    "password": "Solnce544"
}
###
###
POST  http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "gjktn@list.ru",
    "password": "Solnce544"
}
###
admin 57e62b17670b781b2436e80950ac9e08150d0ad5
###
POST  http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 0d33ffbceeb4d0465cc2dfc317e5bad3c0bd10ba

{
    "new_password": "Solnce54",
    "current_password": "Solnce544"
}
###
###
GET http://130.193.42.75/api/v1/titles/
Content-Type: application/json
###
###
GET http://127.0.0.1:8000/api/v1/titles/
Content-Type: application/json
###
###
GET http://127.0.0.1:8000/api/v1/genres/
Content-Type: application/json
###
###
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
"email": "gjktn@list.ru",
"username": "lisa"
}
###
POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
"username": "lisa",
"confirmation_code": "1b29055c-4253-47bf-a08d-34b08078c804"
}
###
POST http://127.0.0.1:8000/api/v1/titles/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYzMjQxNDUxLCJpYXQiOjE2NjI2MzY2NTEsImp0aSI6ImZmYmRhNTczOGYzNTQzZWY4ZmQ5ZmEyMGYzNDFlY2U2IiwidXNlcl9pZCI6MX0.8C8Rl9s_d4dG4_okJXZquEE67l3qGY-Sxey5SLUrNrc

{
"name": "Волшебник Изумрудного города",
"year": 1939,
"description": "Сказочная повесть",
"genre": [
    "classical"
],
"category": "book"
}