# Generated by Django 3.2.15 on 2022-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221002_1730'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_name_color_slug',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='unique_name_slug'),
        ),
    ]
