# Generated by Django 3.2.15 on 2022-10-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221008_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags_th',
            new_name='tag_through',
        ),
    ]
