# Generated by Django 3.2.15 on 2022-09-29 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220929_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='_users_user_subscribed_+', through='users.Subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
